#!/bin/sh
bv -d -g && day -y
# this loads your daily Bible reading and Youtube to daily video in BibleGateway.com
# add --bibleversion=NKJV 
# to use one of the many versions on BibleGateway.com that bv does not have
#
# uncomment this one and comment line 2 if you want to open at esv.org
# bv -d -e && day -y
